import 'dart:collection';

import '../models/country.dart';

final countryMap = UnmodifiableMapView(const <String, Country>{
  'AF': Country(name: 'Afghanistan', dialCode: '+93', isoCode: 'AF'),
  'AX': Country(name: 'Aland Islands', dialCode: '+358', isoCode: 'AX'),
  'AL': Country(name: 'Albania', dialCode: '+355', isoCode: 'AL'),
  'DZ': Country(name: 'Algeria', dialCode: '+213', isoCode: 'DZ'),
  'AS': Country(name: 'American Samoa', dialCode: '+1684', isoCode: 'AS'),
  'AD': Country(name: 'Andorra', dialCode: '+376', isoCode: 'AD'),
  'AO': Country(name: 'Angola', dialCode: '+244', isoCode: 'AO'),
  'AI': Country(name: 'Anguilla', dialCode: '+1264', isoCode: 'AI'),
  'AQ': Country(name: 'Antarctica', dialCode: '+672', isoCode: 'AQ'),
  'AG': Country(name: 'Antigua and Barbuda', dialCode: '+1268', isoCode: 'AG'),
  'AR': Country(name: 'Argentina', dialCode: '+54', isoCode: 'AR'),
  'AM': Country(name: 'Armenia', dialCode: '+374', isoCode: 'AM'),
  'AW': Country(name: 'Aruba', dialCode: '+297', isoCode: 'AW'),
  'AC': Country(name: 'Ascension Island', dialCode: '+247', isoCode: 'AC'),
  'AU': Country(name: 'Australia', dialCode: '+61', isoCode: 'AU'),
  'AT': Country(name: 'Austria', dialCode: '+43', isoCode: 'AT'),
  'AZ': Country(name: 'Azerbaijan', dialCode: '+994', isoCode: 'AZ'),
  'BS': Country(name: 'Bahamas', dialCode: '+1242', isoCode: 'BS'),
  'BH': Country(name: 'Bahrain', dialCode: '+973', isoCode: 'BH'),
  'BD': Country(name: 'Bangladesh', dialCode: '+880', isoCode: 'BD'),
  'BB': Country(name: 'Barbados', dialCode: '+1246', isoCode: 'BB'),
  'BY': Country(name: 'Belarus', dialCode: '+375', isoCode: 'BY'),
  'BE': Country(name: 'Belgium', dialCode: '+32', isoCode: 'BE'),
  'BZ': Country(name: 'Belize', dialCode: '+501', isoCode: 'BZ'),
  'BJ': Country(name: 'Benin', dialCode: '+229', isoCode: 'BJ'),
  'BM': Country(name: 'Bermuda', dialCode: '+1441', isoCode: 'BM'),
  'BT': Country(name: 'Bhutan', dialCode: '+975', isoCode: 'BT'),
  'BO': Country(name: 'Bolivia', dialCode: '+591', isoCode: 'BO'),
  'BA':
      Country(name: 'Bosnia and Herzegovina', dialCode: '+387', isoCode: 'BA'),
  'BW': Country(name: 'Botswana', dialCode: '+267', isoCode: 'BW'),
  'BR': Country(name: 'Brazil', dialCode: '+55', isoCode: 'BR'),
  'IO': Country(
      name: 'British Indian Ocean Territory', dialCode: '+246', isoCode: 'IO'),
  'BN': Country(name: 'Brunei Darussalam', dialCode: '+673', isoCode: 'BN'),
  'BG': Country(name: 'Bulgaria', dialCode: '+359', isoCode: 'BG'),
  'BF': Country(name: 'Burkina Faso', dialCode: '+226', isoCode: 'BF'),
  'BI': Country(name: 'Burundi', dialCode: '+257', isoCode: 'BI'),
  'KH': Country(name: 'Cambodia', dialCode: '+855', isoCode: 'KH'),
  'CM': Country(name: 'Cameroon', dialCode: '+237', isoCode: 'CM'),
  'CA': Country(name: 'Canada', dialCode: '+1', isoCode: 'CA'),
  'CV': Country(name: 'Cape Verde', dialCode: '+238', isoCode: 'CV'),
  'KY': Country(name: 'Cayman Islands', dialCode: '+1345', isoCode: 'KY'),
  'CF': Country(
      name: 'Central African Republic', dialCode: '+236', isoCode: 'CF'),
  'TD': Country(name: 'Chad', dialCode: '+235', isoCode: 'TD'),
  'CL': Country(name: 'Chile', dialCode: '+56', isoCode: 'CL'),
  'CN': Country(name: 'China', dialCode: '+86', isoCode: 'CN'),
  'CX': Country(name: 'Christmas Island', dialCode: '+61', isoCode: 'CX'),
  'CC':
      Country(name: 'Cocos (Keeling) Islands', dialCode: '+61', isoCode: 'CC'),
  'CO': Country(name: 'Colombia', dialCode: '+57', isoCode: 'CO'),
  'KM': Country(name: 'Comoros', dialCode: '+269', isoCode: 'KM'),
  'CG': Country(name: 'Congo', dialCode: '+242', isoCode: 'CG'),
  'CK': Country(name: 'Cook Islands', dialCode: '+682', isoCode: 'CK'),
  'CR': Country(name: 'Costa Rica', dialCode: '+506', isoCode: 'CR'),
  'HR': Country(name: 'Croatia', dialCode: '+385', isoCode: 'HR'),
  'CU': Country(name: 'Cuba', dialCode: '+53', isoCode: 'CU'),
  'CY': Country(name: 'Cyprus', dialCode: '+357', isoCode: 'CY'),
  'CZ': Country(name: 'Czech Republic', dialCode: '+420', isoCode: 'CZ'),
  'CD': Country(
      name: 'Democratic Republic of the Congo',
      dialCode: '+243',
      isoCode: 'CD'),
  'DK': Country(name: 'Denmark', dialCode: '+45', isoCode: 'DK'),
  'DJ': Country(name: 'Djibouti', dialCode: '+253', isoCode: 'DJ'),
  'DM': Country(name: 'Dominica', dialCode: '+1767', isoCode: 'DM'),
  'DO': Country(name: 'Dominican Republic', dialCode: '+1849', isoCode: 'DO'),
  'EC': Country(name: 'Ecuador', dialCode: '+593', isoCode: 'EC'),
  'EG': Country(name: 'Egypt', dialCode: '+20', isoCode: 'EG'),
  'SV': Country(name: 'El Salvador', dialCode: '+503', isoCode: 'SV'),
  'GQ': Country(name: 'Equatorial Guinea', dialCode: '+240', isoCode: 'GQ'),
  'ER': Country(name: 'Eritrea', dialCode: '+291', isoCode: 'ER'),
  'EE': Country(name: 'Estonia', dialCode: '+372', isoCode: 'EE'),
  'SZ': Country(name: 'Eswatini', dialCode: '+268', isoCode: 'SZ'),
  'ET': Country(name: 'Ethiopia', dialCode: '+251', isoCode: 'ET'),
  'FK': Country(
      name: 'Falkland Islands (Malvinas)', dialCode: '+500', isoCode: 'FK'),
  'FO': Country(name: 'Faroe Islands', dialCode: '+298', isoCode: 'FO'),
  'FJ': Country(name: 'Fiji', dialCode: '+679', isoCode: 'FJ'),
  'FI': Country(name: 'Finland', dialCode: '+358', isoCode: 'FI'),
  'FR': Country(name: 'France', dialCode: '+33', isoCode: 'FR'),
  'GF': Country(name: 'French Guiana', dialCode: '+594', isoCode: 'GF'),
  'PF': Country(name: 'French Polynesia', dialCode: '+689', isoCode: 'PF'),
  'GA': Country(name: 'Gabon', dialCode: '+241', isoCode: 'GA'),
  'GM': Country(name: 'Gambia', dialCode: '+220', isoCode: 'GM'),
  'GE': Country(name: 'Georgia', dialCode: '+995', isoCode: 'GE'),
  'DE': Country(name: 'Germany', dialCode: '+49', isoCode: 'DE'),
  'GH': Country(name: 'Ghana', dialCode: '+233', isoCode: 'GH'),
  'GI': Country(name: 'Gibraltar', dialCode: '+350', isoCode: 'GI'),
  'GR': Country(name: 'Greece', dialCode: '+30', isoCode: 'GR'),
  'GL': Country(name: 'Greenland', dialCode: '+299', isoCode: 'GL'),
  'GD': Country(name: 'Grenada', dialCode: '+1473', isoCode: 'GD'),
  'GP': Country(name: 'Guadeloupe', dialCode: '+590', isoCode: 'GP'),
  'GU': Country(name: 'Guam', dialCode: '+1671', isoCode: 'GU'),
  'GT': Country(name: 'Guatemala', dialCode: '+502', isoCode: 'GT'),
  'GG': Country(name: 'Guernsey', dialCode: '+44', isoCode: 'GG'),
  'GN': Country(name: 'Guinea', dialCode: '+224', isoCode: 'GN'),
  'GW': Country(name: 'Guinea-Bissau', dialCode: '+245', isoCode: 'GW'),
  'GY': Country(name: 'Guyana', dialCode: '+592', isoCode: 'GY'),
  'HT': Country(name: 'Haiti', dialCode: '+509', isoCode: 'HT'),
  'VA': Country(
      name: 'Holy See (Vatican City State)', dialCode: '+379', isoCode: 'VA'),
  'HN': Country(name: 'Honduras', dialCode: '+504', isoCode: 'HN'),
  'HK': Country(name: 'Hong Kong', dialCode: '+852', isoCode: 'HK'),
  'HU': Country(name: 'Hungary', dialCode: '+36', isoCode: 'HU'),
  'IS': Country(name: 'Iceland', dialCode: '+354', isoCode: 'IS'),
  'IN': Country(name: 'India', dialCode: '+91', isoCode: 'IN'),
  'ID': Country(name: 'Indonesia', dialCode: '+62', isoCode: 'ID'),
  'IR': Country(name: 'Iran', dialCode: '+98', isoCode: 'IR'),
  'IQ': Country(name: 'Iraq', dialCode: '+964', isoCode: 'IQ'),
  'IE': Country(name: 'Ireland', dialCode: '+353', isoCode: 'IE'),
  'IM': Country(name: 'Isle of Man', dialCode: '+44', isoCode: 'IM'),
  'IL': Country(name: 'Israel', dialCode: '+972', isoCode: 'IL'),
  'IT': Country(name: 'Italy', dialCode: '+39', isoCode: 'IT'),
  'CI': Country(
      name: 'Ivory Coast / Cote d\'Ivoire', dialCode: '+225', isoCode: 'CI'),
  'JM': Country(name: 'Jamaica', dialCode: '+1876', isoCode: 'JM'),
  'JP': Country(name: 'Japan', dialCode: '+81', isoCode: 'JP'),
  'JE': Country(name: 'Jersey', dialCode: '+44', isoCode: 'JE'),
  'JO': Country(name: 'Jordan', dialCode: '+962', isoCode: 'JO'),
  'KZ': Country(name: 'Kazakhstan', dialCode: '+77', isoCode: 'KZ'),
  'KE': Country(name: 'Kenya', dialCode: '+254', isoCode: 'KE'),
  'KI': Country(name: 'Kiribati', dialCode: '+686', isoCode: 'KI'),
  'KP': Country(
      name: 'Korea, Democratic People\'s Republic of Korea',
      dialCode: '+850',
      isoCode: 'KP'),
  'KR': Country(
      name: 'Korea, Republic of South Korea', dialCode: '+82', isoCode: 'KR'),
  'XK': Country(name: 'Kosovo', dialCode: '+383', isoCode: 'XK'),
  'KW': Country(name: 'Kuwait', dialCode: '+965', isoCode: 'KW'),
  'KG': Country(name: 'Kyrgyzstan', dialCode: '+996', isoCode: 'KG'),
  'LA': Country(name: 'Laos', dialCode: '+856', isoCode: 'LA'),
  'LV': Country(name: 'Latvia', dialCode: '+371', isoCode: 'LV'),
  'LB': Country(name: 'Lebanon', dialCode: '+961', isoCode: 'LB'),
  'LS': Country(name: 'Lesotho', dialCode: '+266', isoCode: 'LS'),
  'LR': Country(name: 'Liberia', dialCode: '+231', isoCode: 'LR'),
  'LY': Country(name: 'Libya', dialCode: '+218', isoCode: 'LY'),
  'LI': Country(name: 'Liechtenstein', dialCode: '+423', isoCode: 'LI'),
  'LT': Country(name: 'Lithuania', dialCode: '+370', isoCode: 'LT'),
  'LU': Country(name: 'Luxembourg', dialCode: '+352', isoCode: 'LU'),
  'MO': Country(name: 'Macau', dialCode: '+853', isoCode: 'MO'),
  'MG': Country(name: 'Madagascar', dialCode: '+261', isoCode: 'MG'),
  'MW': Country(name: 'Malawi', dialCode: '+265', isoCode: 'MW'),
  'MY': Country(name: 'Malaysia', dialCode: '+60', isoCode: 'MY'),
  'MV': Country(name: 'Maldives', dialCode: '+960', isoCode: 'MV'),
  'ML': Country(name: 'Mali', dialCode: '+223', isoCode: 'ML'),
  'MT': Country(name: 'Malta', dialCode: '+356', isoCode: 'MT'),
  'MH': Country(name: 'Marshall Islands', dialCode: '+692', isoCode: 'MH'),
  'MQ': Country(name: 'Martinique', dialCode: '+596', isoCode: 'MQ'),
  'MR': Country(name: 'Mauritania', dialCode: '+222', isoCode: 'MR'),
  'MU': Country(name: 'Mauritius', dialCode: '+230', isoCode: 'MU'),
  'YT': Country(name: 'Mayotte', dialCode: '+262', isoCode: 'YT'),
  'MX': Country(name: 'Mexico', dialCode: '+52', isoCode: 'MX'),
  'FM': Country(
      name: 'Micronesia, Federated States of Micronesia',
      dialCode: '+691',
      isoCode: 'FM'),
  'MD': Country(name: 'Moldova', dialCode: '+373', isoCode: 'MD'),
  'MC': Country(name: 'Monaco', dialCode: '+377', isoCode: 'MC'),
  'MN': Country(name: 'Mongolia', dialCode: '+976', isoCode: 'MN'),
  'ME': Country(name: 'Montenegro', dialCode: '+382', isoCode: 'ME'),
  'MS': Country(name: 'Montserrat', dialCode: '+1664', isoCode: 'MS'),
  'MA': Country(name: 'Morocco', dialCode: '+212', isoCode: 'MA'),
  'MZ': Country(name: 'Mozambique', dialCode: '+258', isoCode: 'MZ'),
  'MM': Country(name: 'Myanmar', dialCode: '+95', isoCode: 'MM'),
  'NA': Country(name: 'Namibia', dialCode: '+264', isoCode: 'NA'),
  'NR': Country(name: 'Nauru', dialCode: '+674', isoCode: 'NR'),
  'NP': Country(name: 'Nepal', dialCode: '+977', isoCode: 'NP'),
  'NL': Country(name: 'Netherlands', dialCode: '+31', isoCode: 'NL'),
  // 'AN': Country(name: 'Netherlands Antilles', dialCode: '+599', isoCode: 'AN'),
  'NC': Country(name: 'New Caledonia', dialCode: '+687', isoCode: 'NC'),
  'NZ': Country(name: 'New Zealand', dialCode: '+64', isoCode: 'NZ'),
  'NI': Country(name: 'Nicaragua', dialCode: '+505', isoCode: 'NI'),
  'NE': Country(name: 'Niger', dialCode: '+227', isoCode: 'NE'),
  'NG': Country(name: 'Nigeria', dialCode: '+234', isoCode: 'NG'),
  'NU': Country(name: 'Niue', dialCode: '+683', isoCode: 'NU'),
  'NF': Country(name: 'Norfolk Island', dialCode: '+672', isoCode: 'NF'),
  'MK': Country(name: 'North Macedonia', dialCode: '+389', isoCode: 'MK'),
  'MP': Country(
      name: 'Northern Mariana Islands', dialCode: '+1670', isoCode: 'MP'),
  'NO': Country(name: 'Norway', dialCode: '+47', isoCode: 'NO'),
  'OM': Country(name: 'Oman', dialCode: '+968', isoCode: 'OM'),
  'PK': Country(name: 'Pakistan', dialCode: '+92', isoCode: 'PK'),
  'PW': Country(name: 'Palau', dialCode: '+680', isoCode: 'PW'),
  'PS': Country(name: 'Palestine', dialCode: '+970', isoCode: 'PS'),
  'PA': Country(name: 'Panama', dialCode: '+507', isoCode: 'PA'),
  'PG': Country(name: 'Papua New Guinea', dialCode: '+675', isoCode: 'PG'),
  'PY': Country(name: 'Paraguay', dialCode: '+595', isoCode: 'PY'),
  'PE': Country(name: 'Peru', dialCode: '+51', isoCode: 'PE'),
  'PH': Country(name: 'Philippines', dialCode: '+63', isoCode: 'PH'),
  'PN': Country(name: 'Pitcairn', dialCode: '+872', isoCode: 'PN'),
  'PL': Country(name: 'Poland', dialCode: '+48', isoCode: 'PL'),
  'PT': Country(name: 'Portugal', dialCode: '+351', isoCode: 'PT'),
  'PR': Country(name: 'Puerto Rico', dialCode: '+1939', isoCode: 'PR'),
  'QA': Country(name: 'Qatar', dialCode: '+974', isoCode: 'QA'),
  'RE': Country(name: 'Reunion', dialCode: '+262', isoCode: 'RE'),
  'RO': Country(name: 'Romania', dialCode: '+40', isoCode: 'RO'),
  'RU': Country(name: 'Russia', dialCode: '+7', isoCode: 'RU'),
  'RW': Country(name: 'Rwanda', dialCode: '+250', isoCode: 'RW'),
  'BL': Country(name: 'Saint Barthelemy', dialCode: '+590', isoCode: 'BL'),
  'SH': Country(
      name: 'Saint Helena, Ascension and Tristan Da Cunha',
      dialCode: '+290',
      isoCode: 'SH'),
  'KN':
      Country(name: 'Saint Kitts and Nevis', dialCode: '+1869', isoCode: 'KN'),
  'LC': Country(name: 'Saint Lucia', dialCode: '+1758', isoCode: 'LC'),
  'MF': Country(name: 'Saint Martin', dialCode: '+590', isoCode: 'MF'),
  'PM': Country(
      name: 'Saint Pierre and Miquelon', dialCode: '+508', isoCode: 'PM'),
  'VC': Country(
      name: 'Saint Vincent and the Grenadines',
      dialCode: '+1784',
      isoCode: 'VC'),
  'WS': Country(name: 'Samoa', dialCode: '+685', isoCode: 'WS'),
  'SM': Country(name: 'San Marino', dialCode: '+378', isoCode: 'SM'),
  'ST': Country(name: 'Sao Tome and Principe', dialCode: '+239', isoCode: 'ST'),
  'SA': Country(name: 'Saudi Arabia', dialCode: '+966', isoCode: 'SA'),
  'SN': Country(name: 'Senegal', dialCode: '+221', isoCode: 'SN'),
  'RS': Country(name: 'Serbia', dialCode: '+381', isoCode: 'RS'),
  'SC': Country(name: 'Seychelles', dialCode: '+248', isoCode: 'SC'),
  'SL': Country(name: 'Sierra Leone', dialCode: '+232', isoCode: 'SL'),
  'SG': Country(name: 'Singapore', dialCode: '+65', isoCode: 'SG'),
  'SX': Country(name: 'Sint Maarten', dialCode: '+1721', isoCode: 'SX'),
  'SK': Country(name: 'Slovakia', dialCode: '+421', isoCode: 'SK'),
  'SI': Country(name: 'Slovenia', dialCode: '+386', isoCode: 'SI'),
  'SB': Country(name: 'Solomon Islands', dialCode: '+677', isoCode: 'SB'),
  'SO': Country(name: 'Somalia', dialCode: '+252', isoCode: 'SO'),
  'ZA': Country(name: 'South Africa', dialCode: '+27', isoCode: 'ZA'),
  'GS': Country(
      name: 'South Georgia and the South Sandwich Islands',
      dialCode: '+500',
      isoCode: 'GS'),
  'SS': Country(name: 'South Sudan', dialCode: '+211', isoCode: 'SS'),
  'ES': Country(name: 'Spain', dialCode: '+34', isoCode: 'ES'),
  'LK': Country(name: 'Sri Lanka', dialCode: '+94', isoCode: 'LK'),
  'SD': Country(name: 'Sudan', dialCode: '+249', isoCode: 'SD'),
  'SR': Country(name: 'Suriname', dialCode: '+597', isoCode: 'SR'),
  'SJ': Country(name: 'Svalbard and Jan Mayen', dialCode: '+47', isoCode: 'SJ'),
  'SE': Country(name: 'Sweden', dialCode: '+46', isoCode: 'SE'),
  'CH': Country(name: 'Switzerland', dialCode: '+41', isoCode: 'CH'),
  'SY': Country(name: 'Syrian Arab Republic', dialCode: '+963', isoCode: 'SY'),
  'TW': Country(name: 'Taiwan', dialCode: '+886', isoCode: 'TW'),
  'TJ': Country(name: 'Tajikistan', dialCode: '+992', isoCode: 'TJ'),
  'TZ': Country(
      name: 'Tanzania, United Republic of Tanzania',
      dialCode: '+255',
      isoCode: 'TZ'),
  'TH': Country(name: 'Thailand', dialCode: '+66', isoCode: 'TH'),
  'TL': Country(name: 'Timor-Leste', dialCode: '+670', isoCode: 'TL'),
  'TG': Country(name: 'Togo', dialCode: '+228', isoCode: 'TG'),
  'TK': Country(name: 'Tokelau', dialCode: '+690', isoCode: 'TK'),
  'TO': Country(name: 'Tonga', dialCode: '+676', isoCode: 'TO'),
  'TT': Country(name: 'Trinidad and Tobago', dialCode: '+1868', isoCode: 'TT'),
  'TN': Country(name: 'Tunisia', dialCode: '+216', isoCode: 'TN'),
  'TR': Country(name: 'Turkey', dialCode: '+90', isoCode: 'TR'),
  'TM': Country(name: 'Turkmenistan', dialCode: '+993', isoCode: 'TM'),
  'TC': Country(
      name: 'Turks and Caicos Islands', dialCode: '+1649', isoCode: 'TC'),
  'TV': Country(name: 'Tuvalu', dialCode: '+688', isoCode: 'TV'),
  'UG': Country(name: 'Uganda', dialCode: '+256', isoCode: 'UG'),
  'UA': Country(name: 'Ukraine', dialCode: '+380', isoCode: 'UA'),
  'AE': Country(name: 'United Arab Emirates', dialCode: '+971', isoCode: 'AE'),
  'GB': Country(name: 'United Kingdom', dialCode: '+44', isoCode: 'GB'),
  'US': Country(name: 'United States', dialCode: '+1', isoCode: 'US'),
  // 'UMI': Country(
  //     name: 'United States Minor Outlying Islands',
  //     dialCode: '+246',
  //     isoCode: 'UMI'),
  'UY': Country(name: 'Uruguay', dialCode: '+598', isoCode: 'UY'),
  'UZ': Country(name: 'Uzbekistan', dialCode: '+998', isoCode: 'UZ'),
  'VU': Country(name: 'Vanuatu', dialCode: '+678', isoCode: 'VU'),
  'VE': Country(
      name: 'Venezuela, Bolivarian Republic of Venezuela',
      dialCode: '+58',
      isoCode: 'VE'),
  'VN': Country(name: 'Vietnam', dialCode: '+84', isoCode: 'VN'),
  'VG': Country(
      name: 'Virgin Islands, British', dialCode: '+1284', isoCode: 'VG'),
  'VI': Country(name: 'Virgin Islands, U.S.', dialCode: '+1340', isoCode: 'VI'),
  'WF': Country(name: 'Wallis and Futuna', dialCode: '+681', isoCode: 'WF'),
  'YE': Country(name: 'Yemen', dialCode: '+967', isoCode: 'YE'),
  'ZM': Country(name: 'Zambia', dialCode: '+260', isoCode: 'ZM'),
  'ZW': Country(name: 'Zimbabwe', dialCode: '+263', isoCode: 'ZW')
});
