export 'authentication/pages.dart';
export 'become_tutor/become_tutor_page.dart';
export 'course_ebook/pages.dart';
export 'dashboard/dashboard_page.dart';
export 'message/message_page.dart';
export 'schedule/schedule_page.dart';
export 'tutor/pages.dart';
export 'user/pages.dart';
export 'home_page.dart';
